# Generated by Django 2.2.3 on 2019-07-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userzone', '0002_auto_20190718_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('answertext', models.TextField()),
                ('answeredby', models.CharField(max_length=50)),
                ('qid', models.IntegerField()),
                ('answerddate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('questiontext', models.TextField()),
                ('askedby', models.CharField(max_length=50)),
                ('posteddate', models.CharField(max_length=30)),
            ],
        ),
    ]
